nucleus.mask<-function(blue)
  {
    require(bioimagetools)
    blue0<-try(channel(blue,"blue"))
    if (class(blue0)!="try-error")
      blue<-blue0
    remove(blue0)
    mb<-apply(blue,3,mean)
    mbr<-0.5*sum(range(mb))
    mbr<-which(mbr<mb)
    small<-min(mbr):max(mbr)
    dims0<-dim(blue)
    blue<-blue[,,small]
    dims<-dim(blue)
    blue<-blue-median(blue)
    blue[blue<0]<-0
    blue<-array(blue,dims)
    blue<-blue/max(blue)
    blue<-filter(blue,"var",4,1/3)
    seg<-segment(blue,2,1,inforce.nclust=TRUE,varfixed=TRUE)
    seg$class<-seg$class-1
    X<-dim(blue)[1]
    Y<-dim(blue)[2]
    Z<-dim(blue)[3]
    flip.x<-FALSE
    if(seg$class[1,1,1]==1)flip.x<-TRUE
    if(flip.x)seg$class[X:1,,]<-seg$class
    flip.y<-FALSE
    if(seg$class[1,1,1]==1)flip.y<-TRUE
    if(flip.y)seg$class[,Y:1,]<-seg$class
    flip.z<-FALSE
    if(seg$class[1,1,1]==1)flip.z<-TRUE
    if(flip.z)seg$class[,,Z:1]<-seg$class
    mask0<-1-outside(seg$class,0,15)
    if(flip.x)mask0[X:1,,]<-mask0
    if(flip.y)mask0[,Y:1,]<-mask0
    if(flip.z)mask0[,,Z:1]<-mask0
    mask<-array(0,dims0)
    mask[,,small]<-array(as.integer(mask0),dim(mask0))
    return(mask)
  }

