---
title: "mcd-test"
author: "Volker Schmid"
date: "22 12 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bioimagetools)
library(nucim)
```

## Workflow example

# Installation
```{r eval=FALSE, collapse=TRUE}
setRepositories(ind=c(1,2))
install.packages("nucim")
library(bioimagetools)
library(nucim)
```

# Read image and mask from DAPI
```{r cache=TRUE, echo=TRUE, warning=FALSE, collapse=TRUE}
img = readTIF("http://ex.volkerschmid.de/cell.tif")
sections = dim(img)[4]
x = y = 0.0395
z = 0.125
blue = img[,,3,] 
mask = dapimask(blue, c(x,y,z)*dim(img)[1:3], thresh="auto")
```

# Chromatin compaction classification
```{r cache=TRUE, echo=TRUE, warning=FALSE, collapse=TRUE}
classes = classify(blue, mask, 7, beta=0.1, z=x/z)
tab<-table.n(classes, 7, percentage=TRUE)
barplot(tab, ylab="percentage", xlab="chromatin compaction level",col=heatmap7())
par(pty="s")
img(classes, z=16, col=heatmap7(), mask=mask)
writeTIF(classes, "classes.tif")
```

# Distances of chromatin compaction classes
```{r cache=TRUE, echo=TRUE, warning=FALSE, collapse=TRUE, eval=TRUE}
classes<-readClassTIF("classes.tif")
system.time((distances1 = nearestClassDistances(classes,  voxelsize=c(x,y,z), classes=7, cores=24L)),gcFirst=TRUE)
#system.time((distances2 = nearestClassDistances2(classes,  voxelsize=c(x,y,z), classes=7, cores=16L)),gcFirst=TRUE)
system.time((distances3 = nearestClassDistances3(classes,  voxelsize=c(x,y,z), classes=7, maxdist=2, cores=24L)),gcFirst=TRUE)

plotNearestClassDistances(distances3, method="boxplot",ylim=c(0,1.5))
plotNearestClassDistances(distances1, method="boxplot",ylim=c(0,1.5))

for (i in 1:7)
  for (j in 1:7)
    print(summary(distances1[[i]][[j]]-distances3[[i]][j]]))
```

# Distances of chromatin compaction classes
```{r cache=TRUE, echo=TRUE, warning=FALSE, collapse=TRUE, eval=TRUE}
img<-readClassTIF("classes.tif")
classes<-7
x = y = 0.0395
z = 0.125
voxelsize=c(x,y,z)
cores=1

for (i in 1:7)
  for (j in 1:7)
    {
    print(system.time(test<-ncdWorker2(worker.list[[13]],img, tt, zscale, maxdist, mean(voxelsize[1:2]))))
    print(summary(test))
  }

```